add_newline = true

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

[aws]
format = '[$symbol ($profile)(\($region\))(\[$duration\]) ]($style)'
symbol = "îŒ½"

[buf]
format = '[$symbol ($version) ]($style)'
symbol = "ï’"

[c]
format = '[$symbol ($version(-$name)) ]($style)'
symbol = "î˜"

[cmake]
format = '[$symbol ($version) ]($style)'

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[cobol]
format = '[$symbol ($version)]($style)'

[conda]
format = '[$symbol $environment]($style)'
symbol = "ï„Œ"

[crystal]
format = '[$symbol ($version)]($style)'
symbol = "î˜¯"

[daml]
format = '[$symbol ($version)]($style)'

[dart]
format = '[$symbol ($version)]($style)'
symbol = "î˜"

[deno]
format = '[$symbol ($version)]($style)'

[directory]
read_only = " ó°Œ¾"

[docker_context]
format = '[$symbol ($version)(ğŸ¯ $tfm)]($style)'
symbol = "ïŒˆ"

[elixir]
format = '[$symbol ($version \(OTP $otp_version\))]($style)'
symbol = "î˜­"

[elm]
format = '[$symbol ($version)]($style)'
symbol = "î˜¬"

[fennel]
format = '[$symbol ($version)]($style)'
symbol = "îš¯"

[fossil_branch]
format = '[$symbol $branch]($style)'
symbol = "ï˜"

[gcloud]
format = '[$symbol $account(@$domain)(\($region\))]($style)'

[git_branch]
format = '[$symbol $branch]($style)'
symbol = "ï˜"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed )]($style)"
style = "cyan"
conflicted = "â‡¡â‡£"
# untracked = " âœ©"
untracked = "?"
modified = "*"
staged = " ï——"
renamed = "âœ"
deleted = "âœ–"
stashed = "â‰¡"

# [git_state]
# format = '\([$state($progress_current/$progress_total)]($style)\)'
# style = "bright-black"

[golang]
format = '[$symbol $branch]($style)'
symbol = "î˜§"

[guix_shell]
format = '[$symbol ]($style)'
symbol = "ïŒ¥"

[haskell]
format = '[$symbol $version ]($style)'
symbol = "î·"

[haxe]
format = '[$symbol $version ]($style)'
symbol = "î™¦"

[helm]
format = '[$symbol $version ]($style)'

[hg_branch]
format = '[$symbol $branch]($style)'
symbol = "ï˜"

[hostname]
ssh_symbol = "î¬"

[java]
format = '[$symbol $version ]($style)'
symbol = "î‰–"

[julia]
format = '[$symbol $version ]($style)'
symbol = "î˜¤"

[kotlin]
format = '[$symbol $version ]($style)'
symbol = "î˜´"

[kubernetes]
format = '[$symbol $context( \($namespace\))]($style)'

[lua]
format = '[$symbol $version ]($style)'
symbol = "î˜ "

[memory_usage]
format = '$symbol [$ram( | $swap)]($style)'
symbol = "ó°›"

[meson]
format = '[$symbol $project]($style)'
symbol = "ó°”·"

[nim]
format = '[$symbol $version ]($style)'
symbol = "ó°†¥"

[nix_shell]
format = '[$symbol $state( \($name\))]($style)'
symbol = "ïŒ“"

[nodejs]
format = '[$symbol ($version) ]($style)'
symbol = "îœ˜"

[ocaml]
format = '[$symbol ($version)(\($switch_indicator$switch_name\))]($style)'
symbol = "î™º"

[os.symbols]
Alpaquita = "îª¢"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "ï…»"
Arch = "ïŒƒ"
Artix = "ïŒŸ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "îŠ"
Emscripten = "ïˆ…"
EndeavourOS = "ï†—"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Garuda = "ó°›“"
Gentoo = "ïŒ"
HardenedBSD = "ó°Œ"
Illumos = "ó°ˆ¸"
Linux = "ïŒš"
Mabox = "î¬©"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Mariner = "ï‡"
MidnightBSD = "ï††"
Mint = "ïŒ"
NetBSD = "ï€¤"
NixOS = "ïŒ“"
OpenBSD = "ó°ˆº"
openSUSE = "ïŒ”"
OracleLinux = "ó°Œ·"
Pop = "ïŒª"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Redox = "ó°€˜"
Solus = "ó° ³"
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ïˆ­"
Windows = "ó°²"

[os]
format = '[$symbol ]($style)'

[package]
format = '[$symbol $version ]($style)'
symbol = "ó°—"

[perl]
format = '[$symbol $version ]($style)'
symbol = "î™¾"

[php]
format = '[$symbol $version ]($style)'
symbol = "î˜ˆ"

[pijul_channel]
format = '[$symbol $channel]($style)'
symbol = "ï˜"

[purescript]
format = '[$symbol $version ]($style)'

[python]
format = '[${symbol} ${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)'
symbol = "îˆµ"

[raku]
format = '[$symbol $version ]($style)'

[red]
format = '[$symbol $version ]($style)'

[rlang]
symbol = "ó°Ÿ”"

[ruby]
format = '[$symbol $version ]($style)'
symbol = "î‘"

[rust]
format = '[$symbol $version ]($style)'
symbol = "î¨"

[scala]
format = '[$symbol $version ]($style)'
symbol = "îœ·"

[spack]
format = '[$symbol $environment]($style)'

[swift]
format = '[$symbol $version ]($style)'
symbol = "î•"

[terraform]
format = '[$symbol $workspace]($style)'

[time]
format = '[$time ]($style)'

[username]
format = '[$user ]($style)'

[vagrant]
format = '[$symbol ($version)]($style)'

[vlang]
format = '[$symbol ($version)]($style)'

[zig]
format = '[$symbol $version ]($style)'
symbol = "îš©"
